services:
  redis:
    image: redis:7.2
    restart: unless-stopped
    environment:
      REDIS_USERNAME: default
      REDIS_PASSWORD: default
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10
    tmpfs: /data

  service:
    build: .
    env_file:
      - .env
    environment:
      - REDIS=redis://default:default@redis:6379/0
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - 3000:3000
